# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('is_published', models.BooleanField(default=True, verbose_name='publish')),
                ('created', models.DateTimeField(verbose_name='created')),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ('-created',),
                'verbose_name': 'news',
            },
        ),
    ]
